source 'http://rubygems.org'

# The gems you'll need for generating your site on your development machine.
# The deployment strategy you use determines what you need in production, if
# anything.
#
group :development do
  gem 'jekyll', '~> 0.11.0'
  gem 'compass', '~> 0.11.0'
end

# If your deployment target has you running Ruby, you might have some gems
# listed here. This will be the case if you deploy to Heroku.
#
group :production do

end
