#! /usr/bin/env ruby

$:.unshift File.dirname(__FILE__)

require 'octopress'
require 'irb'
require 'irb/completion'

ARGV.delete_if do |arg|
  if arg =~ /(.+)=(.+)/
    ENV[$1] = $2
  else
    false
  end
end

IRB.start
