source "https://rubygems.org"

gem "rake", "~> 10.0"

group :test do
  # Yes, minitest is part of Ruby 1.9, but certain features we use such as 'subject'
  # in spec-style tests weren't in the version that shipped with 1.9.2.  To deal
  # with this, we use the gem version.
  gem "minitest"
end
