$:.unshift File.dirname(__FILE__) # For use/testing when no gem is installed

require "rubygems"
require 'octopress'
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.pattern = "spec/**/*_spec.rb"
end
