source :rubygems
gemspec

gem 'rake'
gem 'rdoc'

# group :debug do
#   gem 'ruby-debug19'
# end

group :test do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'fakefs'
  gem 'webmock'
  gem 'aruba', '~> 0.4.11'
  #if we are on travis ci ignore these
  unless ENV["CI"]
    gem 'rb-fsevent'
    gem 'ruby_gntp', '~> 0.3.4'
  end
end